version: "3"
services:
  jenkins:
    image: bartthewacky/wacky-jenkins-kat
    ports:
      - 8080:8080
      - 50000:50000
      - 465:465
      - 9515:9515
    environment:
      - JENKINS_SLAVE_AGENT_PORT=50000
      - LANG=C.UTF-8
      - JENKINS_UC=https://updates.jenkins.io
      - PWD=/
      - HOME=/var/jenkins_home
      - COPY_REFERENCE_FILE_LOG=/var/jenkins_home/copy_reference_file.log
      - JENKINS_HOME=/var/jenkins_home
      - CA_CERTIFICATES_JAVA_VERSION=20170531+nmu1
      - JAVA_DEBIAN_VERSION=8u181-b13-2~deb9u1
      - TERM=xterm
      - JENKINS_INCREMENTALS_REPO_MIRROR=https://repo.jenkins-ci.org/incrementals
      - SHLVL=1
      - JENKINS_UC_EXPERIMENTAL=https://updates.jenkins.io/experimental
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - JENKINS_VERSION=2.151
      - JENKINS_HOST_HOME=/data/jenkins
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    build: 
      context: wacky-jenkins-kat/.
    healthcheck:
        test: ["CMD", "curl", "-f", "http://192.168.99.101:8080"]
        interval: 45s
        timeout: 10s
        retries: 5
     
  agent-chrome:
    image: bartthewacky/wacky-agent
    environment:
      - LANG=C.UTF-8
      - MAVEN_HOME=/usr/share/maven
      - JAVA_HOME=/docker-java-home
      - JAVA_VERSION=8u171
      - PWD=/home/jenkins
      - HOME=/home/jenkins
      - JENKINS_AGENT_NAME=agent_chrome
      - JENKINS_SECRET=829f4bb45f8deeff3eae48ffdc9c08b30d48f65ce9023d5b2ffecb3bce41906b
      - MAVEN_CONFIG=/home/jenkins/.m2
      - JENKINS_HOME=/home/jenkins/agent
      - CA_CERTIFICATES_JAVA_VERSION=20170531+nmu1
      - AGENT_WORKDIR=/home/jenkins/agent
      - JAVA_DEBIAN_VERSION=8u171-b11-1~deb9u1
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - SQUASH_TA_HOME=/home/jenkins/agent
      - JENKINS_URL=http://192.168.99.101:8080/
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/shm:/dev/shm
    build:
      context: wacky-agent-chrome/.
      args: 
        - u="jenkins"
    # deploy:
      # replicas: 1
      # restart_policy:
        # condition: on-failure
        # delay: 30s
        # max_attempts: 2
    depends_on:
      - jenkins
    links: 
      - jenkins
    restart: on-failure
    
  agent-firefox:
    image: bartthewacky/wacky-agent
    environment:
      - LANG=C.UTF-8
      - MAVEN_HOME=/usr/share/maven
      - JAVA_HOME=/docker-java-home
      - JAVA_VERSION=8u171
      - PWD=/home/jenkins
      - HOME=/home/jenkins
      - JENKINS_AGENT_NAME=agent_firefox
      - JENKINS_SECRET=af0c43cc22c7db5f8738ba4bdb3f54528e995ec6ff44e068f97398fea4234d0c
      - MAVEN_CONFIG=/home/jenkins/.m2
      - JENKINS_HOME=/home/jenkins/agent
      - CA_CERTIFICATES_JAVA_VERSION=20170531+nmu1
      - AGENT_WORKDIR=/home/jenkins/agent
      - JAVA_DEBIAN_VERSION=8u171-b11-1~deb9u1
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - SQUASH_TA_HOME=/home/jenkins/agent
      - JENKINS_URL=http://192.168.99.101:8080/
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: wacky-agent-firefox/.
      args: 
        - u="jenkins"
    # deploy:
      # replicas: 1
      # restart_policy:
        # condition: on-failure
        # delay: 600s
        # max_attempts: 2
        # window: 120s
    depends_on:
      - jenkins
    links: 
      - jenkins
    restart: on-failure

volumes:
  jenkins-home:
  jenkins-data: